name: Check Naming Convention

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  check-naming-convention:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v2.1.0

      - name: Check naming convention
        run: |
          find . -name "*.java" | while read file; do
            if grep -q 'import [A-Z]' $file; then
              echo "ERROR: Found uppercase letter in import statement in $file"
              exit 1
            fi
            if grep -q 'package [a-z]' $file; then
              echo "ERROR: Found lowercase letter in package statement in $file"
              exit 1
            fi
            if grep -q 'class [a-z]' $file; then
              echo "ERROR: Found lowercase letter at the beginning of a class name in $file"
              exit 1
            fi
          done
