on:
  pull_request:
    branches:
      - main

jobs:
  control-changed-files:
    name: List14

    runs-on: ubuntu-latest
    steps:
      
      - name: check-naming
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get list changed files
        run: |
          changed_files=$(git diff --name-only HEAD~1 | grep -v ".github/workflows/check-naming.yaml")
          echo "$changed_files"
