on:
  pull_request:
    branches:
      - main

jobs:
  control-changed-files:
    name: list5
    runs-on: ubuntu-latest
    steps:
    
      - name: check-naming
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get list changed files
        run:
          LEVEL=4
          changed_files=$(git diff --name-only)
          for file in $changed_files; do
             echo $file
          done;
