on:
  pull_request:
    branches:
      - main

jobs:
  control-changed-files:
    name: List7

    runs-on: ubuntu-latest
    steps:
      
      - name: check-naming
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get list changed files
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD | xargs)
          echo "$changed_files"
